### ISSUE TITLE
Click on fullScreen icon not performing.

### ISSUE THREAD

**Issue by MohammadHilal1** [codedthemes/datta-able-free-react-admin-template#5]
Clicking on the fullScreen icon makes the app fullScreen.And clicking back the icon for making it normal is freezing the app and do not let perform any operation
And looking at the console shows me following error.
![Button _ Datta Able Free React + Redux Admin Template - Google Chrome 1_22_2022 3_43_09 PM](https://user-images.githubusercontent.com/77286095/150634507-f0ab07a3-fbea-45c5-9c53-e43ebf01b0a6.png)
![Button _ Datta Able Free React + Redux Admin Template - Google Chrome 1_22_2022 3_43_26 PM](https://user-images.githubusercontent.com/77286095/150634515-bbc97fca-6e7a-4519-8682-a45d821d64a3.png)

**Comment by codedthemes** [comment]
the full-screen feature is no longer available.
